function [name,value]= analyze(RawData,varargin)

substr=strsplit(RawData,'/');


filename=strsplit(substr{2},'.');

substr=strsplit(RawData,'Input');
output=[substr{1} 'Output'];

if ~isfolder(output)
    mkdir(output);
end

mkdir([output '/met']);

value={'',...
    filename{1},...
    strtrim(RawData),...
    output,...
    '4.1',...
    '0.2',...
    '1024',...
    '8.334e-4',...
    '99',...
    '7',...
    '123.25',...
    '/home/compimglab/.lcmodel/basis-sets/gamma_press_te30_123mhz_v1.basis',...
    'F',...
    'F',...
    [output '\Input\h2o\RAW'],...
    [output '\' filename{1} '.table'],...
    [output '\' filename{1} '.ps'],...
    [output '/met/RAW' ],...
    '30' ,...
    [output '\' filename{1} '.csv'],...
    [output '\' filename{1} '.coord'],...
    '9',...
    '14',...
    '6',...
    [output '\' filename{1} '.print'],...
    '0.01',...
    ''};



name={'$LCMODL',...
    'title=',...
    'srcraw=',...
    'savdir=',...
    'ppmst=',...
    'ppmend=',...
    'nunfil=',...
    'deltat=',...
    'neach=',...
    'ltable=',...
    'hzpppm=',...
    'filbas=',...
    'doecc=',...
    'dows=',...
    'filh2o=',...
    'filtab=',...
    'filps=',...
    'filraw=',...
    'echot=' ,...
    'filcsv=',...
    'filcoo=',...
    'lcoord=',...
    'lcsv=',...
    'lprint=',...
    'filpri=',...
    'WDLINE(6)=',...
    '$END'};






for i =1:length(varargin)
    
    subset=strsplit(varargin{i},'=');
    indx=find(strcmp(name,[subset{1} '=']));
    value{indx}=subset{2};
    
end

fid=fopen('run61616161.control','w');

for i=1:length(value)
    if ~isempty(str2num(value{i})) | isempty(value{i})
        formatSpec = '%s %s\n';
    else
        formatSpec = '%s ''%s''\n';
        
    end
    
    fprintf(fid,formatSpec,name{i},value{i})
end
fclose(fid)

end


